### ISSUE TITLE
JNA vs JNI

### ISSUE THREAD

**Issue by BeeHiveJava** [redpois0n/nativewindowlib#2]
Hello,

I figured that JNA was increasing my file size by a little more than 1mb, which is okay in most cases. But in some cases I like to have a file as small as possible. Recently I've done some updates ([here](https://github.com/U2ForMeJava/nativewindowlib)) that upgrade this library to JNI, instead of JNA, resulting in a jar size of 28kb. The API contains little to no changes for the end user(I renamed only one method, I believe).

I'd be happy if you have a look at it and see what you think. See if there's room for some merging. I'll gladly take any criticism and points of improvement.

Cheers,

U2 For Me

**Comment by wille** [comment]
Please attach native code

**Comment by BeeHiveJava** [comment]
Added, see [native](https://github.com/U2ForMeJava/nativewindowlib/tree/master/src/native).

**Comment by wille** [comment]
Very impressive, since I never used JNI before, and my C sucks. I'll play some with this, and try to do my own version, and keep it in C. I think you used a bit too much native code, like creating lists etc, but I might be very wrong

Nice work

**Comment by BeeHiveJava** [comment]
I felt like that was the best way, to populate a List. It's very possible to just pass an array of ints. By the way, using vector or list in C++ consumes more bytes, I wanted to keep the library as small as possible.

**Comment by wille** [comment]
I see :-)

I am going to try to do this in pure C which I think is easier to use than C++. I'll let you know if I get stuck. Perfect opportunity to learn :)

**Comment by BeeHiveJava** [comment]
Alright :-)

I should add your XMPP. Expect an invite soon.

**Comment by wille** [comment]
I prefer email, hit me up at red@cmail.nu
